package com.ticketpass.api.order;
import com.ticketpass.api.settlement.*;
import java.util.UUID;
import org.springframework.stereotype.Service;
@Service
public class BuyerReceiptConfirmationService {
 private final BuyerReceiptConfirmationCommand command; private final SettlementReleaseOperationRepository operations; private final OrderFulfillmentRepository fulfillments; private final SettlementReleaseClaimService claims; private final SettlementProvider provider; private final SettlementReleaseFinalizer finalizer; private final OrderRepository orders;
 public BuyerReceiptConfirmationService(BuyerReceiptConfirmationCommand c, SettlementReleaseOperationRepository o, OrderFulfillmentRepository fulf, SettlementReleaseClaimService claims, SettlementProvider p, SettlementReleaseFinalizer f, OrderRepository orders){command=c;operations=o;fulfillments=fulf;this.claims=claims;provider=p;finalizer=f;this.orders=orders;}
 public BuyerReceiptConfirmationResponse confirm(UUID buyerId,String rawOrderId){UUID orderId=parse(rawOrderId);command.accept(buyerId,orderId); SettlementReleaseOperationEntity operation=claims.claim(orderId); if(operation!=null){OrderEntity order=orders.findByIdForResponse(orderId).orElseThrow();SettlementReleaseResult result=provider.release(new SettlementReleaseRequest(orderId,order.getAmountMinor(),order.getCurrency(),operation.getIdempotencyKey(),operation.getProviderOperationId()));finalizer.finalizeResult(orderId,result);} return response(orders.findByIdForResponse(orderId).orElseThrow(), fulfillments.findByOrderId(orderId).orElseThrow()); }
 private static UUID parse(String raw){try{return UUID.fromString(raw);}catch(IllegalArgumentException e){throw new com.ticketpass.api.common.ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"orderId must be a UUID");}}
 private static BuyerReceiptConfirmationResponse response(OrderEntity o, OrderFulfillmentEntity f){return new BuyerReceiptConfirmationResponse(o.getId().toString(),o.getStatus().name(),f.getTransferStatus().name(),f.getSettlementStatus().name(),o.getPaidAt(),f.getTransferDeadlineAt(),f.getSellerConfirmedAt(),f.getBuyerConfirmedAt(),f.getSettlementReleasedAt(),"NONE",f.getSettlementStatus()!=SettlementStatus.RELEASED_TO_SELLER,o.getAmountMinor(),o.getCurrency(),new BuyerReceiptConfirmationResponse.Event(o.getListing().getEvent().getName(),o.getListing().getEvent().getStartsAt(),o.getListing().getEvent().getVenue(),o.getListing().getEvent().getCity()),new BuyerReceiptConfirmationResponse.Ticket(o.getListing().getTicketType(),o.getListing().getSeatInfo(),o.getListing().getTransferMethod().name()));}
}
